### ISSUE TITLE
Malformed query returns incorrect data from model (should not return anything)

### ISSUE THREAD

**Issue by xscheiner** [derbyjs/derby#494] opened 2015-03-06 17:07 UTC
Total accidental discovery here, which I thought was my own defect at first. A developer was consuming a route on my api and sent me valid but incorrectly formatted json. This caused something which, on investigation, seems to point to a problem with Derby models.

The malformed json looked like this:

``` javascript
{
  "users": [ "email", "firstName", "lastName"]
}
```

This should have been an array of objects each of which had the keys email, firstName and lastName with associated values. I have corrected my code to check the structure of the payload rather than just that it is valid json, which was my bad, but, here is what I turned up with a bit more investigation.

For each object in the array, I pass along the email to a method which queries users from my users db and assigns ownership of some data to them. The method looks like this:

``` javascript
var checkIfUserExists = function (model, userData, next) {
    var query = {
        email: userData.email
    };
    var query$ = model.query('auths', query);
    model.fetch(query$, function (err) {
       if (err) {
            return next(err);
       }
       next(null, query$.get());
    });
};
```

With the malformed data, I got a query object that looked like this:

``` javascript
{ email: undefined }
```

When the model fetched, instead of returning no data, or an error, it returned the first user it found in the collection, which meant a user not concerned in the query got their data updated incorrectly. Passing the same query to mongo from the command line, returns:

``` javascript
error: {
    "$err" : "Can't canonicalize query: BadValue cannot compare to undefined",
    "code" : 17287
}
```

As I say, I suspect this is a problem somewhere in your model code, though it could also be in the mongo drivers, which is why I am raising it at the top level as I am not sure where it truly belongs.

**Comment by enjalot** [comment] 2015-03-06 21:20
I could see this happening because of JavaScript's weird falsy logic. I imagine when the query is serialized the undefined turns into false or null, which would result in a valid query in mongo.
this should probably be fixed in LiveDB or ShareJS, but thank you for bringing it up here (it's easier to just track the bugs at the top level).

**Comment by xscheiner** [comment] 2015-03-09 11:46
Should I create an issue in one of those? Thing is, even if a valid query were to pass, for example, email: null, that should not return any data because none of the users actually have a null email address.

**Comment by enjalot** [comment] 2015-03-09 19:07
We can use this issue for now.

Actually mongo will return any document that doesn't have an email key with {email: null} it gets treated the same as {$exists: false}

**Comment by xscheiner** [comment] 2015-03-10 11:12
Sorry, I didn't clarify my comment. You are correct that any users with no email will be returned. Our application logic does not allow any such users in the collection and the users that are coming back from the query do have content in their email key.

**Comment by craigbeck** [comment] 2024-05-29 18:04
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.

**Closed by craigbeck** 2024-05-29 18:04 UTC
