### ISSUE TITLE
attributeContext issue, parameters wrapped in ParentWrapper

### ISSUE THREAD

**Issue by ile** [derbyjs/derby#418] opened 2014-05-17 14:31 UTC
In `app.proto.testing(param)` the `param` comes wrapped in `ParentWrapper` in some cases, while I don't think they should be wrapped like that.

It happens if I pass the same attributes into view components/templates twice in a row, like:

``` html
<view name="discuss:comments" comments="{{#root._page.comments}}"></view>
```

``` html
<comments:><view name="comments-header" comments="{{@comments}}"></view>
```

And the issue can be seen in:

``` html
<comments-header:>{{testing(@comments)}}
```

``` coffeescript
app.proto.testing = (c) -> console.log(c) # prints ParentWrapper
```

(Maybe I'm using attributes a bit too much, not sure.)

Anyway, I made a quick workaround, but I don't know if it's right:

https://github.com/ilkkah/derby-templates/commit/bea663c7e9f14991b9518c85fc7ef66012b436d9

There seemed to be a lot similar code like `if (value instanceof templates.Template) value = ...` and this my change is only in this one function, so maybe it wasn't made correctly. But hopefully it helps anyway.

~~Actually I just noticed that this helps only when rendering client side. Server side rendering still has the issue.~~

**Comment by azotova** [comment] 2015-06-23 10:45
I am experiencing a similar issue:
Component1: in Component1, I use Component2 and pass on an object.

```
<view name="component2" user = {{_myUser}}></view>
```
Component2: in Component2, I use the user as an argument to a couple of functions and pass it on to view3.
I checked in the controller that I can get access to the correct user object (the original _myUser) by using both `this.getAttribute` and `this.model.get`. Nearly identical functions firstName and lastName below work fine, although I use `@user` as an argument for one of the functions and `user` for the other.
```
<component2:>
  <div>{{firstName(@user)}}</div>
  <div>{{lastName(user)}}</div>  
  <view name="view3" user={{@user}}></view>
```
In view3, I do not get access to the user object.

```
<view3:>
  {{testing(@user)}} //get undefined when logging, not even ParentWrapper.
```

When I replace the last line in Component2 with `<view name="view3" user={{user}}></view>` without `@` sign, I get the correct object in View3. Is this the expected behavior or am I doing something wrong? I would have understood if `firstName(@user)` did not work as well, but it works just fine.

**Comment by droganov** [comment] 2015-06-23 12:02
Hello, we're passing arguments without an @ mark and it works for us

**Comment by azotova** [comment] 2015-06-23 12:38
Thanks! When I pass arguments without an `@` mark, it works for me too.  I just was wondering why I can use `@user` (from my example) in some cases (Component2 in my example, function firstName) but can't pass it on as an attribute in the same component. It's a little confusing because usually if something is defined (and `@user` seems to be defined), it can be used for any purpose.

**Comment by droganov** [comment] 2015-06-23 14:32
I don't know the idea behind that. The fact is that we observe that @-marked attributes are rendered correctly and passed to sub-components as a reference. Maybe this is a bug, maybe not. We've been observing this for about a year.

**Comment by craigbeck** [comment] 2024-05-29 17:09
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.

**Closed by craigbeck** 2024-05-29 17:09 UTC
Labels: Investigate
