### ISSUE TITLE
Problem with {{each}} loop and custom html tags defined by component arrays attribute

### ISSUE THREAD

**Issue by mattbrun** [derbyjs/derby#501] opened 2015-04-15 18:32 UTC
In short, if I use the following everything works fine
```html
<tabs selectedIndex="{{0}}">
  <pane title="One"><b>Hi</b></pane>
  <pane title="Two">ho</pane>
  <pane title="Three">away</pane>
  <pane title="Four">we <span class="highlight">{{_page.punchline}}!</span></pane>
</tabs>
```

if I use the following code, the `tabs` component is not visualized
```html
<tabs selectedIndex="{{0}}">
  {{each _page.tabs as #tab}}
    <pane title="{{#tab.title}}"><b>{{#tab.text}}</b></pane>
  {{/each}}
</tabs>
```

Codepen: http://codepen.io/mattbrun/pen/JogZdr?editors=101

**Comment by zag2art** [comment] 2015-04-16 05:47
As I understand that is by design. Arrays-attributes are not for dynamic rendering. Nate mentioned this somewhere.

**Comment by icaliman** [comment] 2015-04-16 13:48
https://github.com/derbyjs/derby/issues/416

**Comment by enjalot** [comment] 2015-04-16 20:16
thanks for linking, closing as per reasoning in #416

**Closed by enjalot** 2015-04-16 20:16 UTC
